version: '3.8'

networks:
  cassandra-net:
    ipam:
      config:
          - subnet: 172.20.0.0/24

services: 
    jupyter:
      user: root
      build: ./jupyter/
      environment:
        JUPYTER_ENABLE_LAB: "yes"
        GRANT_SUDO: "yes"
      ports:
        - 8888:8888
      networks:
        cassandra-net:
          ipv4_address: 172.20.0.5
      volumes:
        - "jupyter_data:/home/jovyan/work"

    cassandra0:
      build: ./cassandra/
      mem_limit: 1g
      volumes:
        - "cassandra_data_0:/var/lib/cassandra"
      environment:
        - "CASSANDRA_SEEDS=cassandra0"
        - "CASSANDRA_CLUSTER_NAME=Test Cluster"
        - "CASSANDRA_DC=se1"
        - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
        - "MAX_HEAP_SIZE=1G"
        - "HEAP_NEWSIZE=100M"
      networks:
        cassandra-net:
          ipv4_address: 172.20.0.6
      ports:
        - "9040:9042"
      healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 15s
        timeout: 15s
        retries: 100

    cassandra1:
      build: ./cassandra/
      mem_limit: 1g
      volumes:
        - "cassandra_data_1:/var/lib/cassandra"
      environment:
        - "CASSANDRA_SEEDS=cassandra0"
        - "CASSANDRA_CLUSTER_NAME=Test Cluster"
        - "CASSANDRA_DC=se1"
        - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
        - "MAX_HEAP_SIZE=1G"
        - "HEAP_NEWSIZE=100M"
      depends_on:
        cassandra0:
          condition: service_healthy
      networks:
        cassandra-net:
          ipv4_address: 172.20.0.7
      ports:
        - "9041:9042"
      healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 15s
        timeout: 15s
        retries: 100

    cassandra2:
      build: ./cassandra/
      mem_limit: 1g
      volumes:
        - "cassandra_data_2:/var/lib/cassandra"
      environment:
        - "CASSANDRA_SEEDS=cassandra0"
        - "CASSANDRA_CLUSTER_NAME=Test Cluster"
        - "CASSANDRA_DC=se1"
        - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
        - "MAX_HEAP_SIZE=1G"
        - "HEAP_NEWSIZE=100M"
      networks:
        cassandra-net:
          ipv4_address: 172.20.0.8
      ports:
        - "9042:9042"
      depends_on:
        cassandra1:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 15s
        timeout: 15s
        retries: 100

volumes:
  cassandra_data_0:
  cassandra_data_1:
  cassandra_data_2:
  jupyter_data: