name: Start Docker Compose Test

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: isbang/compose-action@v1.0.0
        with:
          compose-file: './docker-compose.yaml'
          down-flags: '--volumes'
