name: Start Docker Compose Test

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [macos-latest]
        # os: [macos-latest, ubuntu-latest, "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'
      - run: docker-compose up -d --build --force-recreate
      - run: docker ps
      # - run: docker ps > docker-ps.txt
