name: Start Docker Compose Test

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # os: [macos-latest, ubuntu-latest, "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: isbang/compose-action@v1.0.0
        with:
          down-flags: '--volumes'
      # - run: docker-compose up -d --build --force-recreate
      - run: docker ps
      # - run: docker ps > docker-ps.txt
